package jp.girky.wf_noctuahub.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF286A56)
val onPrimaryLight = Color(0xFFE4FFF2)
val primaryContainerLight = Color(0xFFAEF0D7)
val onPrimaryContainerLight = Color(0xFF175C49)
val secondaryLight = Color(0xFF4C645A)
val onSecondaryLight = Color(0xFFE4FFF2)
val secondaryContainerLight = Color(0xFFCEE9DC)
val onSecondaryContainerLight = Color(0xFF3F574D)
val tertiaryLight = Color(0xFF2E6771)
val onTertiaryLight = Color(0xFFEDFBFF)
val tertiaryContainerLight = Color(0xFFB7EFFB)
val onTertiaryContainerLight = Color(0xFF215B65)
val errorLight = Color(0xFFA83836)
val onErrorLight = Color(0xFFFFF7F6)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF6E0A12)
val backgroundLight = Color(0xFFF6FAF6)
val onBackgroundLight = Color(0xFF2B3530)
val surfaceLight = Color(0xFFF6FAF6)
val onSurfaceLight = Color(0xFF2B3530)
val surfaceVariantLight = Color(0xFFDAE5DF)
val onSurfaceVariantLight = Color(0xFF57615C)
val outlineLight = Color(0xFF737D78)
val outlineVariantLight = Color(0xFFAAB4AE)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF0B0F0D)
val inverseOnSurfaceLight = Color(0xFF999E9B)
val inversePrimaryLight = Color(0xFFB9FCE2)
val surfaceDimLight = Color(0xFFD2DDD6)
val surfaceBrightLight = Color(0xFFF6FAF6)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEFF5F0)
val surfaceContainerLight = Color(0xFFE8F0EA)
val surfaceContainerHighLight = Color(0xFFE1EAE4)
val surfaceContainerHighestLight = Color(0xFFDAE5DF)

val primaryDark = Color(0xFF9FD1BD)
val onPrimaryDark = Color(0xFF174839)
val primaryContainerDark = Color(0xFF2C5B4B)
val onPrimaryContainerDark = Color(0xFFBCEED9)
val secondaryDark = Color(0xFFB2CCC0)
val onSecondaryDark = Color(0xFF2E453C)
val secondaryContainerDark = Color(0xFF294037)
val onSecondaryContainerDark = Color(0xFFABC5B9)
val tertiaryDark = Color(0xFFDDF9FF)
val onTertiaryDark = Color(0xFF2B636E)
val tertiaryContainerDark = Color(0xFFB7EFFB)
val onTertiaryContainerDark = Color(0xFF205B65)
val errorDark = Color(0xFFFA746F)
val onErrorDark = Color(0xFF490006)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFF9993)
val backgroundDark = Color(0xFF0B0F0D)
val onBackgroundDark = Color(0xFFDDE8E1)
val surfaceDark = Color(0xFF0B0F0D)
val onSurfaceDark = Color(0xFFDDE8E1)
val surfaceVariantDark = Color(0xFF404A45)
val onSurfaceVariantDark = Color(0xFFA3AEA8)
val outlineDark = Color(0xFF6D7872)
val outlineVariantDark = Color(0xFF404A45)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFF6FAF6)
val inverseOnSurfaceDark = Color(0xFF515653)
val inversePrimaryDark = Color(0xFF396858)
val surfaceDimDark = Color(0xFF0B0F0D)
val surfaceBrightDark = Color(0xFF242E2A)
val surfaceContainerLowestDark = Color(0xFF000000)
val surfaceContainerLowDark = Color(0xFF0E1512)
val surfaceContainerDark = Color(0xFF141B18)
val surfaceContainerHighDark = Color(0xFF19211E)
val surfaceContainerHighestDark = Color(0xFF1E2824)

object CustomColors {
    var black = false
}
